#Production Settings
project:
  name: "Postgres_ETL_Production_Run"
  log_level: "INFO"

spark_params:
  spark.executor.memory: "4g"
  spark.driver.memory: "2g"
  spark.sql.shuffle.partitions: "200"

database:
  url: "jdbc:postgresql://localhost:5432/postgres"
  driver: "org.postgresql.Driver"

tables:
  source_sales: "public.sales_transactions"
  source_products: "public.product_master"
  target_report: "public.category_sales_report"
  metadata_table: "public.pipeline_run_metadata"

load_settings:
  mode: "append"